name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libreadline-dev coreutils

    # Step 3: Configure and build the project
    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    # Step 4: Run the tests
    - name: Run tests
      run: |
        ./build/test 
